/**
 * Generated by orval
 * Do not edit manually.
 * Bouw.API | v1
 * OpenAPI spec version: 1.0.0
 */
export interface CreateTicketRequest {
  /** @nullable */
  userInput: string | null
}

export interface TicketResponse {
  id: string
  title: string
  userInput: string
  status: string
  llmResponse: string
  createdAt: string
  updatedAt: string
}

export interface WorkflowActionResponse {
  id: string
  key: string
  type: string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  position: number | string
  configJson: string
}

export interface WorkflowStepResponse {
  id: string
  key: string
  name: string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  position: number | string
  actions: WorkflowActionResponse[]
}

export interface WorkflowResponse {
  id: string
  name: string
  description: string
  status: string
  steps: WorkflowStepResponse[]
}

export type getWorkflowResponse200 = {
  data: WorkflowResponse
  status: 200
}

export type getWorkflowResponse404 = {
  data: void
  status: 404
}

export type getWorkflowResponseSuccess = getWorkflowResponse200 & {
  headers: Headers
}
export type getWorkflowResponseError = getWorkflowResponse404 & {
  headers: Headers
}

export type getWorkflowResponse = getWorkflowResponseSuccess | getWorkflowResponseError

export const getGetWorkflowUrl = (id: string) => {
  return `/workflows/${id}`
}

export const getWorkflow = async (
  id: string,
  options?: RequestInit,
): Promise<getWorkflowResponse> => {
  const res = await fetch(getGetWorkflowUrl(id), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getWorkflowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWorkflowResponse
}

export type getWorkflowsResponse200 = {
  data: WorkflowResponse[]
  status: 200
}

export type getWorkflowsResponseSuccess = getWorkflowsResponse200 & {
  headers: Headers
}
export type getWorkflowsResponse = getWorkflowsResponseSuccess

export const getGetWorkflowsUrl = () => {
  return `/workflows`
}

export const getWorkflows = async (options?: RequestInit): Promise<getWorkflowsResponse> => {
  const res = await fetch(getGetWorkflowsUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getWorkflowsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWorkflowsResponse
}

export type createTicketResponse201 = {
  data: TicketResponse
  status: 201
}

export type createTicketResponse400 = {
  data: void
  status: 400
}

export type createTicketResponseSuccess = createTicketResponse201 & {
  headers: Headers
}
export type createTicketResponseError = createTicketResponse400 & {
  headers: Headers
}

export type createTicketResponse = createTicketResponseSuccess | createTicketResponseError

export const getCreateTicketUrl = () => {
  return `/tickets`
}

export const createTicket = async (
  createTicketRequest: CreateTicketRequest,
  options?: RequestInit,
): Promise<createTicketResponse> => {
  const res = await fetch(getCreateTicketUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createTicketRequest),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: createTicketResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createTicketResponse
}

export type getTicketsResponse200 = {
  data: TicketResponse[]
  status: 200
}

export type getTicketsResponseSuccess = getTicketsResponse200 & {
  headers: Headers
}
export type getTicketsResponse = getTicketsResponseSuccess

export const getGetTicketsUrl = () => {
  return `/tickets`
}

export const getTickets = async (options?: RequestInit): Promise<getTicketsResponse> => {
  const res = await fetch(getGetTicketsUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getTicketsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTicketsResponse
}

export type getTicketResponse200 = {
  data: TicketResponse
  status: 200
}

export type getTicketResponse404 = {
  data: void
  status: 404
}

export type getTicketResponseSuccess = getTicketResponse200 & {
  headers: Headers
}
export type getTicketResponseError = getTicketResponse404 & {
  headers: Headers
}

export type getTicketResponse = getTicketResponseSuccess | getTicketResponseError

export const getGetTicketUrl = (id: string) => {
  return `/tickets/${id}`
}

export const getTicket = async (id: string, options?: RequestInit): Promise<getTicketResponse> => {
  const res = await fetch(getGetTicketUrl(id), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getTicketResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTicketResponse
}
