/**
 * Generated by orval
 * Do not edit manually.
 * Bouw.API | v1
 * OpenAPI spec version: 1.0.0
 */
export interface WorkflowActionResponse {
  id: string
  key: string
  type: string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  position: number | string
  configJson: string
}

export interface WorkflowStepResponse {
  id: string
  key: string
  name: string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  position: number | string
  actions: WorkflowActionResponse[]
}

export interface WorkflowResponse {
  id: string
  name: string
  description: string
  status: string
  steps: WorkflowStepResponse[]
}

export type getWorkflowResponse200 = {
  data: WorkflowResponse
  status: 200
}

export type getWorkflowResponse404 = {
  data: void
  status: 404
}

export type getWorkflowResponseSuccess = getWorkflowResponse200 & {
  headers: Headers
}
export type getWorkflowResponseError = getWorkflowResponse404 & {
  headers: Headers
}

export type getWorkflowResponse = getWorkflowResponseSuccess | getWorkflowResponseError

export const getGetWorkflowUrl = (id: string) => {
  return `/workflows/${id}`
}

export const getWorkflow = async (
  id: string,
  options?: RequestInit,
): Promise<getWorkflowResponse> => {
  const res = await fetch(getGetWorkflowUrl(id), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getWorkflowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWorkflowResponse
}

export type getWorkflowsResponse200 = {
  data: WorkflowResponse[]
  status: 200
}

export type getWorkflowsResponseSuccess = getWorkflowsResponse200 & {
  headers: Headers
}
export type getWorkflowsResponse = getWorkflowsResponseSuccess

export const getGetWorkflowsUrl = () => {
  return `/workflows`
}

export const getWorkflows = async (options?: RequestInit): Promise<getWorkflowsResponse> => {
  const res = await fetch(getGetWorkflowsUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getWorkflowsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWorkflowsResponse
}
