import { defineConfig } from 'orval'

export default defineConfig({
  api: {
    input: {
      target: '../api/spec.json',
    },
    output: {
      target: 'src/lib/api.generated.ts',
      client: 'fetch',
      mode: 'single',
      formatter: 'prettier',
      override: {
        header: (info) => [
          'Generated by orval',
          'Do not edit manually.',
          `${info.title}`,
          `OpenAPI spec version: ${info.version}`,
        ],
      },
    },
  },
})
